# Generated by Django 5.0 on 2025-05-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_schooladmin_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='arrival_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='departure_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
