# Generated by Django 5.0 on 2025-05-26 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_staff_fcm_token_student_fcm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooladmin',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
