# Generated by Django 5.2.1 on 2025-06-16 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='review',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
